### ISSUE TITLE
XCIST Documentation

### ISSUE THREAD

**Issue by BBuijtenhuis** [xcist/main#1]
Hi there,

I am currently trying to implement your amazing software for some CT simulations. 
I however noticed that the documents "User manual - for users, by developers" and "Theory and Implementation - for advanced users and developers, by developers" are not available right now. Is there a way to obtain these documents?

Thanks in advance.

Kind regards,
BBuijtenhuis

**Comment by PaulFitzGerald** [comment]
Hi BBuijtenhuis,

We have not yet produced this documentation. I will update the website to show that.

In the mean time, please use the Wiki to get started, and let me know how it goes for you. This software is in a very early stage - please be patient as we develop further.

Thanks for your interest!
Paul

**Comment by PaulFitzGerald** [comment]
Please find our Wiki at https://github.com/xcist/documentation/wiki

And please join our project! 

Best regards,
Paul

**Comment by BBuijtenhuis** [comment]
Thank you @PaulFitzGerald for the quick reply!

I got the simulation working, but for some reason I can not reconstruct a sharp image.
As there is no reconstruction algorithm implemented (yet), I was trying to reconstruct the CatSim logo using simple Filtered Back Projection (ramp filter). But the image seems to have some magnification artifacts.

Can you maybe help me in the right direction? I have changed a lot of parameters but without much succes.


![CatSim_Logo 360 projections FBP](https://user-images.githubusercontent.com/83346454/133763405-14f6a599-1d7b-4d71-8ad9-8610c5c80ac8.png)

**Comment by MingyeWu** [comment]
Hi @BBuijtenhuis 
This looks like a geometry mismatch.
I think probably it's the pixel size, it seems you doubled the pixel size.
Note that at the detector side, the pixel size is 1mm; but at the rotation center, it should be scaled by sid/sdd.
