### ISSUE TITLE
Add to_upper/to_lower case checking for cfg files

### ISSUE THREAD

**Issue by osandvold302** [xcist/main#19]
Error in running 0.1.6 catsim, new install, windows 11

`catsim/pyfiles/Xray_filter.py` contains material array ['al', 'graphite', 'cu', 'ti']
`catsim/pyfiles/Detection_prefilter.py` contains material array with 'al'

Both throw exception in `CommonTools.py` line 119

Would recommend adding a to_lower check for both inputs and against material files stored in `materials/`

**Comment by MingyeWu** [comment]
Thanks! Issue fixed.
