### ISSUE TITLE
nCAT_main.c does not compile

### ISSUE THREAD

**Issue by ltldlzltl** [xcist/main#21]
I tried to run the XCAT example and found that those nCAT-related functions were not included in the DLL. I checked `clib_build\MakeWindows64` and other related files, `nCAT_main.c` is not compiled at all. None of the `MakeVariables_*` files includes it. It works fine after I added `nCAT_main.c` to the end of `MakeVariables_1`. 

I have recompiled the DLL with some changes in the C code so I'm not sure if the original DLL in the repo has the same problem.

**Comment by MingyeWu** [comment]
I have fixed the compiling script issue, thanks!
I have double checked the dll and so file, the ncat functions are there.
Maybe it was because your local file was not updated?

**Comment by ltldlzltl** [comment]
I recompiled the dll file yesterday with the scripts in the repo, that's the reason why those ncat functions are not in my dll. 
Thanks for the quick fix.
