### ISSUE TITLE
Phantom_NCAT.py compatibility with new XCAT Version 2 .nrb files

### ISSUE THREAD

**Issue by jarydchristie** [xcist/main#22]
I have run an experiment using the "experiment_XCAT50.py" file as a template with the vmale50_chest_phantom.nrb file provided on the repository. However, when I attempt to use my own XCAT50.nrb file created from the XCAT Version 2 code I get a few errors. The first was in the Phantom_NCAT.py file where I edited the "materialList" in "def set_material" and removed "ncat_" from the list. However now it is giving me an error at the "Starting to parse nCAT phatom" stage saying "allocation error in cp_matrix" or "allocation error in bp_matrix". This causes either the kernel to die on jupyter notebook or the code to stop in the cmd line. All other versions of the code works except when I attempt to use my own generated .nrb phantom. Any ideas how to resolve this?

**Comment by MingyeWu** [comment]
(For this version) XCAT phantom files doesn't contain the material names that link to material data files, instead, it contains the indices of the materials. And in Phantom_NCAT.py, materialList maps material names with the indices. So, as long as the material files exist, you can change the materialList freely. Therefore, I think the issue is the format/compatibility of your phantom file. Could you compare the two XCAT files?

**Comment by jarydchristie** [comment]
When I compared the two files the format of them seem similar but their contents are slightly different. For example when I open the files to look at the line by line code your "vmale50_chest_phantom.nrb" file starts like: 

chest_surface_skin
26
50 :M
53 :N
U Knot Vector
0.000000
0.000000
0.000000
0.000000
0.020000
0.040000
0.060000
0.080000
0.100000
0.120000
0.140000
0.160000
0.180000
0.200000

whereas my .nrb files start like: 

head
128 :M
103 :N
U Knot Vector
0
0
0
0
0.01
0.02
0.03
0.04
0.05
0.06
0.07
0.08
0.09
0.1

Additionally, I cannot load the vmale50_chest_phantom.nrb into rhino3d to visualize it but I can with my .nrb phantoms. I should also say that even the phantoms I got directly from the XCAT group without any alteration still gives this error.

**Comment by MingyeWu** [comment]
The issue is the missing material index. For example, 
chest_surface_skin  -- object name
26  -- material index
50 :M
53 :N
U Knot Vector
...

So you will need to add material index after the object name in your phantom file.

**Comment by purepani** [comment]
Hi,
While this was closed, it would be great if the library supported the new format out of the box without having to manually format the file. I couldn't quite figure out where the modifications should be made to make a PR for it immediately, but, as far as I can tell, it looks like XCAT(the dxcat2 cli) outputs an organ list file which contains the index under MU_ID(at least if I'm understanding correctly).
