### ISSUE TITLE
Precision issue in forward projection

### ISSUE THREAD

**Issue by ltldlzltl** [xcist/main#26]
Hi all, 
I have run an experiment to simulate dual-energy CT scan under fan-beam geometry and got material maps with severe noise even if I have turned off noises in the Physics.cfg. After checking the projection data, I found that there was intensity variations between nearby views (see the horizontal stripes in the following image). 
![1669778457143](https://user-images.githubusercontent.com/10810309/204699832-033033b7-a746-416d-85e4-d071b66d48e5.png)
Those variations got magnified after a simple projection-domain material decomposition. 
![1669778679523](https://user-images.githubusercontent.com/10810309/204700283-c767c935-2a6c-46a9-9990-b5e7d059ce77.png)
To ensure that is irrelevent to phantom used, I have run another simulation on a water cylinder and the variations still exist in the results. 
![1669778972270](https://user-images.githubusercontent.com/10810309/204700888-7006b7f5-9577-4162-a521-3b6655a12131.png)
![1669778992500](https://user-images.githubusercontent.com/10810309/204700932-afc565cc-faf2-4f55-ae84-9d7726fd6917.png)
I haven't dived into the C code but I think there might be some precision issues in the forward projection step. 

Best, 
Tianling Lyu

**Comment by MingyeWu** [comment]
Hi Tianling, could you try run it with single energy? If the variation disappears, then there must be some issue in the energy switching part. If the variation still exists, could you try to run the example and compare it with your sim code?

**Comment by ltldlzltl** [comment]
I believe this issue is irrelevent to the dual-energy scan because I did not switch energy level in one simulation. The high energy scan and the low energy scan were simulated seperately under the same protocol and here I only depict the low energy projection data. Also, the water cylinder phantom is tested with single energy and the variation still exists. 
I will try the example code and check the results.

**Comment by ltldlzltl** [comment]
> Hi Tianling, could you try to run it with single energy? If the variation disappears, then there must be some issue in the energy switching part. If the variation still exists, could you try to run the example and compare it with your sim code?

Hi Mingye, 
I have ran the example code provided in the repo (examples/Sim_Sample.py) with some parameters modified to fit my need. Here is the additional code:
```python
ct.physics.enableQuantumNoise = 0
ct.physics.enableElectronicNoise = 0
ct.protocol.viewsPerRotation = 800
ct.protocol.viewCount = ct.protocol.viewsPerRotation
ct.protocol.stopViewId = ct.protocol.viewCount-1
ct.protocol.maxPrep = -1
```
The code works fine with detectorRowCount=16 but after I set the detectorRowCount to 1 to simulate fan-beam geometry, the variation appears. 
Here is the output from the 8th row when detectorRowCount=16 (window=[10,11]).
![1669792013049](https://user-images.githubusercontent.com/10810309/204730141-7e3436c3-4e08-45ec-84fc-956180449cc3.png)
Here is the output when detectorRowCount=1 (window=[10,11]).
![1669792078107](https://user-images.githubusercontent.com/10810309/204730343-6eede6eb-6aa0-4213-a4c7-f92086fb51b1.png)
Any idea why this happens?

**Comment by zhangjy-ge** [comment]
If you can post parameters in your cfg files, maybe I can try to reproduce your error and see what is wrong.

**Comment by ltldlzltl** [comment]
> If you can post parameters in your cfg files, maybe I can try to reproduce your error and see what is wrong.

All cfg files remain unchanged except for those parameters listed in my previous comment. 
Here is the testing code.
```python
import catsim as xc
ct = xc.CatSim("./cfg/Phantom_Sample", "./cfg/Scanner_Sample_generic", "./cfg/Protocol_Sample_axial")  # initialization
##--------- Make changes to parameters (optional)
ct.resultsName = "test"
ct.scanner.detectorRowsPerMod = 1
ct.scanner.detectorRowCount = ct.scanner.detectorRowsPerMod
ct.physics.enableQuantumNoise = 0
ct.physics.enableElectronicNoise = 0
ct.protocol.viewsPerRotation = 800
ct.protocol.viewCount = ct.protocol.viewsPerRotation
ct.protocol.stopViewId = ct.protocol.viewCount-1
ct.protocol.maxPrep = -1

##--------- Run simulation
ct.run_all()  # run the scans defined by protocol.scanTypes
```

**Comment by zhangjy-ge** [comment]
I was not able to reproduce similar variations for ct.scanner.detectorRowsPerMod = 1. Could you tell me which OS you run the code and when did you check out the xcist code?
![image](https://user-images.githubusercontent.com/100655819/205672226-6ed4eefb-62f2-4983-8415-59a9c23b1e65.png)

**Comment by ltldlzltl** [comment]
> 

I checked my code and found that this issue came from my modified 3D projection. I added OpenMP related code for acceleration and it somehow introduced those variations. 

Sorry for the time wasted...
