### ISSUE TITLE
Relation between scan angle and view number

### ISSUE THREAD

**Issue by ltldlzltl** [xcist/main#3]
Hi guys, 

I was simulating the projection data in half-scan mode and attempting to implement that by altering `protocol.viewPerRotation` and `protocol.viewCount` entries in the protocol config file. 
```
protocol.viewsPerRotation = 20
protocol.viewCount = 10
```
However, things do not operate the way I would like them to. The resulting projection data only covers about 90 or 100 degrees. I checked the source code and found that the scanned angle is directly related to the scanning time, which is defined by `protocol.viewsPerRotation`, `protocol.viewCount`, `protocol.rotationTime` and `protocol.dutyRatio`. The scanned angle would be '180*0.6=108 degrees' since I specified 'protocol.dutyRatio = 0.6' in my protocol file (not quite sure about that). Here's what I received after printing source angle beta for each view.
```bash
beta=-0.062832
beta=0.125664
beta=0.314159
beta=0.502655
beta=0.691150
beta=0.879646
beta=1.068142
beta=1.256637
beta=1.445133
beta=1.633628
Scan sim time: 794.1 s
```
This design, in my opinion, is quite counterintuitive. Why would `dutyRatio` impact the scan angle?

Best regards, 
Tianling Lyu

**Comment by MingyeWu** [comment]
Updated catsim/OneScan.py and fixed the bug.

**Comment by ltldlzltl** [comment]
> Updated catsim/OneScan.py and fixed the bug.

Thanks for the quick fix! Just a minor issue: there is a missing colon in the new catsim/OneScan.py (line 112).

**Comment by MingyeWu** [comment]
Ah yes, thanks for the finding! Fixed it now.
