### ISSUE TITLE
Filenames issue in evaluation script

### ISSUE THREAD

**Issue by AnderBiguri** [xcist/main#33]
In [experiment_01_CatSimLogo_SimAndRecon](https://github.com/xcist/main/tree/master/examples/evaluation/experiment_01_CatSimLogo_SimAndRecon) , the code looks for `CatSimLogo_1024.json`, which does not exist. The file name in the phantoms is `CatSim_logo_1024.json`

**Comment by zhangjy-ge** [comment]
thanks, this has been fixed
