### ISSUE TITLE
Bug in evaluation script 1

### ISSUE THREAD

**Issue by AnderBiguri** [xcist/main#34]
https://github.com/xcist/main/blob/3fd43cb3b154130d28f52a181653eeb97efbfcd7/examples/evaluation/experiment_01_CatSimLogo_SimAndRecon/pyfiles/experiment_CatSimLogo.py#L514

Should be

`cfg.recon.do_Recon=True`

Or an error occurs in recon.py

**Comment by AnderBiguri** [comment]
Actually there are many many bugs in these scripts, not just the do_recon. For example, the evaluation script 2 looks for the voxel phantoms in the folder it itself creates, not in the folders next to the results folder, as the documentation would suggest.

**Comment by zhangjy-ge** [comment]
the do_Recon bug is fixed. As for other bugs in the "evaluation" folder, please understand that we are continuously improving the code so it happens that some parameters are out-of-date. We will fix those problems in the future.

**Comment by AnderBiguri** [comment]
@zhangjy-ge absolutely, sorry, I didn't meant to sound rude! 
These things are hard to maintain, I completely understand! Just letting you know, so its documented for future fixes :)

**Comment by zhangjy-ge** [comment]
no worries, in fact your reports are helpful for our future improvements so we welcome them - just some of them will only be fixed after some other work.
