### ISSUE TITLE
How to simulate based on generated files

### ISSUE THREAD

**Issue by zhangjinglin23** [xcist/main#35]
I used the code of "DICOM_to_voxelized_phantom.py"and data of "example_abdomen_DICOMs_Philips" provided by you to generate the following files. 
<img width="337" alt="2c195fcc5b85e05b01e91fa77fb6bb6" src="https://user-images.githubusercontent.com/122517108/224040864-849c6357-ed24-41bd-984a-67278d58b83e.png">

May I ask how to apply them to simulation?
Thank you for your answer.

**Comment by zhangjy-ge** [comment]
As long as you have the JSON file, you may use it as input to the "phantom.filename". Check this for an example: https://github.com/xcist/main/blob/master/examples/cfg/Phantom_Sample.cfg
