### ISSUE TITLE
Scatter Convolution Model

### ISSUE THREAD

**Issue by xiaogengen-007** [xcist/main#66]
Hi,

Thanks for the great work. I am interested in understanding the scatter model used in the simulation.

I noticed in gecatsim/pyfiles/Scatter_ConvolutionModel.py, scatter is only calculated for the first subview and replicated for other subviews.
```
# Scatter is low frequency signal and computational expensive, we only calculate it at the first subview.
    if subViewId == 0:
```

What is the definition of subview? How accurate is this assumption for scatter simulation?

Thank you!

**Comment by MingyeWu** [comment]
Sub view is the sub sampling of views. Scatter is low frequency signal, usually this is a good approximation.

**Comment by xiaogengen-007** [comment]
Thanks for the quick reply. Could you please help me clarify that if "sub sampling of views" is
   (1. subsampling of views when intra-view sampling is used
   (2. something like uniformly downsampling the detector element

I saw the following code, so I am expecting the former.
gecatsim/pyfiles/OneScan.py
> cfg.sim.subViewCount = cfg.physics.viewSampleCount

gecatsim/cfg/Physics_Default.cfg
> physics.viewSampleCount = 2                 # number of samples of each view angle range in rotational direction 

Thank you!

**Comment by MingyeWu** [comment]
Yes, you're right. Sub view sampling is the rotation sampling within a view.
