### ISSUE TITLE
Creating Analytic Phantom

### ISSUE THREAD

**Issue by tims3900** [xcist/main#69]
Hello,
I'm interested in creating an analytic phantom and was wondering if there is any documentation available for reference. While I understand how to shift the phantom in the xy direction, I'm curious if there are techniques to modify its length along the z-axis. Specifically, I'm interested in adjusting the phantom's appearance across multiple slices, allowing certain aspects to appear or disappear as needed. Also is there any way to create more complex shapes from equations or is the analytic phantom limited to elliptical shapes.

**Comment by zhangjy-ge** [comment]
Hi,

- _While I understand how to shift the phantom in the xy direction, I'm curious if there are techniques to modify its length along the z-axis._ Yes, you can change length in the z-axis by modifying the third value of `object.half_axes(1,:) = [108.000000 108.000000 50.000000];` in phantom file like `https://github.com/xcist/main/blob/master/gecatsim/phantom/W20.ppm`
- _Specifically, I'm interested in adjusting the phantom's appearance across multiple slices, allowing certain aspects to appear or disappear as needed_. I am not sure about this question. Did you mean change X/Y size at different z positions? If yes, you can achieve this by using multiple analytic objects with different offset/size, I guess.
- _Also is there any way to create more complex shapes from equations or is the analytic phantom limited to elliptical shapes._ So far we only support limited number of shapes including elliptical shapes. If you want to use complex shapes, I would suggest you to use voxelized or NCAT phantoms.

**Comment by tims3900** [comment]
Thank you for the quick response. I just had another question regarding which shapes are supported by the software and if there is any documentation I can look towards to better understand how to implement these other shapes.

**Comment by zhangjy-ge** [comment]
It seems you have deleted one of your comments about if there are other shapes that are supported by xcist. I would still answer it here for future reference.

We do have plans to support the following shapes in analytic phantom:
`Ellipsoid, Cylinder, Torus, Cone, Hyperboloid2, Hyperboloid1, VesselSeg, Box`
, which can be specified in `object.shape` by an integer, e.g., 1 (for ellipsoid) or 2 (for cylinder). However, not all shapes are implemented as of now and you may see some shapes not working.

**Comment by tims3900** [comment]
Just to clarify, with all the example analytic phantoms such as `W20.ppm` contained in the repository having `object.shape = 0` this means that every analytic object is being defined as an ellipsoid? Looking towards the method Phantom_Analytic_BoundObjects in `Phantom_Analytic.py` I am assuming that the `typ` variable refers to the `object.shape`. Does this mean that the program only supports up to index 2 for the `object.shape`?

**Comment by zhangjy-ge** [comment]
I made a typo in the previous post. It should be `object.type` not `object.shape`. `object.shape` Used only for the torus object to define the thickness relative to the radius of curvature. Sorry for the confusion
