### ISSUE TITLE
Multislice Spiral Imaging with Non-Zero Table Speed

### ISSUE THREAD

**Issue by MshGhazale** [xcist/main#73]
Hello there,

Do the implementations you have developed support multislice curve detector geometry in spiral imaging mode with a non-zero table speed?

In the paper you referenced, the table speed was zero, which corresponds to conventional imaging mode. If you have implemented this, is there an example available?

**Comment by brandonjnelsonFDA** [comment]
I had a similar question, I've been doing serial axial acquisitions by incrementing `protocol.startZ` by `scanner.detectorRowsPerMod`*`scanner.detectorRowSize`, that lets me scan a whole volume with greater z range than the detector coverage. I'm sure there's a better way but I can't find examples either.

The [dose recon code](https://github.com/xcist/main/blob/4d0e50f016558c4bb64efd413d594925d0f00570/gecatsim/dose/pyfiles/catdoserecon.py#L116) has some hints that it changing table speed, rotationTime, and viewsPerRotation should yield longer z coverage, but I havent been able to see the difference when I try
